services:
  spark-master:
    networks:
      - spark_net
    image: docker.io/bitnami/spark:3.5
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
      - SPARK_USER=spark
    ports:
      - 8080:8080

  spark-worker-node:
    networks:
      - spark_net
    image: docker.io/bitnami/spark:3.5
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_MEMORY=1G
      - SPARK_WORKER_CORES=2
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
      - SPARK_USER=spark

  minio:
    restart: always
    user: root
    image: 'bitnami/minio:latest'
    ports:
      - '9000:9000'
      - '9001:9001'
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=minio-admin
      - MINIO_DATA_DIR=/opt/minio_data
    networks:
      - spark_net
    volumes:
      # меняем тут
      - ./minio_data:/opt/minio_data

  jupyter-edge-node:
    networks:
      - spark_net
    build: .
    ports:
      - 8888:8888
      - 4040:4040
    volumes:
      # меняем тут
      - ./jupyter/conf:/root/.jupyter
      - ./jupyter/root_dir:/hw2

networks:
  spark_net:
    driver: bridge

