FROM mirror.gcr.io/apache/hadoop:3

USER root
RUN yum update -y

RUN yum install -y python3 python3-pip gcc libffi6 libffi-dev && yum clean all

ENV PATH="${PATH}:/usr/bin/python3"

RUN rm /bin/sh && ln -s /bin/bash /bin/sh

RUN python3 -m pip install --upgrade pip
RUN python3 -m pip install jupyter